// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxnW0tH83C6ZmLypTa6n0H53LiVnycwjw',
    appId: '1:847963801196:web:02fb792b8eaf644414ba49',
    messagingSenderId: '847963801196',
    projectId: 'fruits-hub-app-c1fa0',
    authDomain: 'fruits-hub-app-c1fa0.firebaseapp.com',
    storageBucket: 'fruits-hub-app-c1fa0.firebasestorage.app',
    measurementId: 'G-TPK6KZD5HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIyzjlkhblIfD18GlY6xhZZKOmAIxLWQI',
    appId: '1:847963801196:android:0aa61e934d9181b314ba49',
    messagingSenderId: '847963801196',
    projectId: 'fruits-hub-app-c1fa0',
    storageBucket: 'fruits-hub-app-c1fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZf_XoZoOM1GJc5mAvFQkACxDqlzRgDE',
    appId: '1:847963801196:ios:4319441747642f4514ba49',
    messagingSenderId: '847963801196',
    projectId: 'fruits-hub-app-c1fa0',
    storageBucket: 'fruits-hub-app-c1fa0.firebasestorage.app',
    androidClientId: '847963801196-t6c3bslpiut1k9grnn6vgovkef12pmoe.apps.googleusercontent.com',
    iosClientId: '847963801196-cbgkn2di3rs22hp6iqia6ke5nj49m0u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtZf_XoZoOM1GJc5mAvFQkACxDqlzRgDE',
    appId: '1:847963801196:ios:4319441747642f4514ba49',
    messagingSenderId: '847963801196',
    projectId: 'fruits-hub-app-c1fa0',
    storageBucket: 'fruits-hub-app-c1fa0.firebasestorage.app',
    androidClientId: '847963801196-t6c3bslpiut1k9grnn6vgovkef12pmoe.apps.googleusercontent.com',
    iosClientId: '847963801196-cbgkn2di3rs22hp6iqia6ke5nj49m0u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxnW0tH83C6ZmLypTa6n0H53LiVnycwjw',
    appId: '1:847963801196:web:acd50402fc6f54e614ba49',
    messagingSenderId: '847963801196',
    projectId: 'fruits-hub-app-c1fa0',
    authDomain: 'fruits-hub-app-c1fa0.firebaseapp.com',
    storageBucket: 'fruits-hub-app-c1fa0.firebasestorage.app',
    measurementId: 'G-7V027XZ1TE',
  );
}
